### ISSUE TITLE
[RadSideDrawer] Random Exception after build

### ISSUE THREAD

**Issue by DimitrisRK** [ProgressNS/nativescript-ui-feedback#1438]
### Tell us about the problem
When building application, there are times that the following error is thrown because of RadSideDrawer:
```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2366)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5322)
System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
System.err:     at dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:5350)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
System.err:     ... 11 more
System.err: Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err:     at dalvik.system.DexFile.defineClassNative(Native Method)
System.err:     at dalvik.system.DexFile.defineClass(DexFile.java:222)
System.err:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
System.err:     at dalvik.system.DexPathList.findClass(DexPathList.java:322)
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
System.err:     at com.tns.DexFactory.resolveClass(DexFactory.java:78)
System.err:     at com.tns.ClassResolver.resolveClass(ClassResolver.java:25)
System.err:     at com.tns.Runtime.resolveClass(Runtime.java:729)
System.err:     ... 21 more
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2366)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5322)
System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
System.err:     at dalvik.system.NativeStart.main(Native Method)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:5350)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
System.err:     ... 11 more
System.err: Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
System.err:     at dalvik.system.DexFile.defineClassNative(Native Method)
System.err:     at dalvik.system.DexFile.defineClass(DexFile.java:222)
System.err:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
System.err:     at dalvik.system.DexPathList.findClass(DexPathList.java:322)
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
System.err:     at com.tns.DexFactory.resolveClass(DexFactory.java:78)
System.err:     at com.tns.ClassResolver.resolveClass(ClassResolver.java:25)
System.err:     at com.tns.Runtime.resolveClass(Runtime.java:729)
System.err:     ... 21 more
```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** nativescript-ui-sidedrawer ^8.0.1
- **CLI:** 6.7.4
- **Cross-platform modules:** 6.5.5
- **Runtime(s):** 6.5.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Perform changes that would force 'tns run' to build anew
2. Exception is thrown on application start

Application is based on 'SideDrawer' sample app from 'tns create'.

**Comment by DimitrisRK** [comment]
Looks like issue was solved when I updated android platform from 6.5.0 to 6.5.1. Still, it might be RadSideDrawer plugin's first time installation that might be causing this issue.
