### ISSUE TITLE
Nativescript-ui-sidedrawer > 9.0.0-rc.1 gives error in ngcc step

### ISSUE THREAD

**Issue by crowmagnumb** [ProgressNS/nativescript-ui-feedback#1448]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_

Both

### Please provide the following version numbers that your issue occurs with:

I get the following error on my postinstall script `ngcc --properties es2015 module main --first-only` if I increase the `nativescript-ui-sidedrawer` to above 9.0.0-rc.1 (e.g. 9.0.0-rc.2 or 9.0.0-rc.3)...

```
Error: Error on worker #4: Error: The given rootPath undefined is not a file of the program.
    at getRootFileOrFail (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:2324:19)
    at Esm2015ReflectionHost.computePublicDtsDeclarationMap (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:1648:27)
    at Esm2015ReflectionHost.getDtsDeclaration (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:458:53)
    at DelegatingReflectionHost.getDtsDeclaration (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:62:34)
    at Object.wrapTypeReference (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:460:34)
    at Object.extractDirectiveMetadata (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:256:27)
    at ComponentDecoratorHandler.analyze (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:145:47)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:346:40)
    at analyze (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:298:58)
    at _loop_1 (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:320:21)
    at ClusterMaster.onWorkerMessage (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/home/ken/dev/animalus/ng10/ng-core/node_modules/tslib/tslib.js:140:27)
    at Object.next (/home/ken/dev/animalus/ng10/ng-core/node_modules/tslib/tslib.js:121:57)
    at /home/ken/dev/animalus/ng10/ng-core/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/ken/dev/animalus/ng10/ng-core/node_modules/tslib/tslib.js:110:16)
    at EventEmitter.<anonymous> (/home/ken/dev/animalus/ng10/ng-core/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:203:13)
```
Relevant parts of `package.json`:

```
    "dependencies": {
        "@angular/animations": "~10.0.0",
        "@angular/cdk": "~10.0.0",
        "@angular/common": "~10.0.0",
        "@angular/compiler": "~10.0.0",
        "@angular/core": "~10.0.0",
        "@angular/flex-layout": "^10.0.0-beta.32",
        "@angular/forms": "~10.0.0",
        "@angular/material": "~10.0.0",
        "@angular/material-moment-adapter": "~10.0.0",
        "@angular/platform-browser": "~10.0.0",
        "@angular/platform-browser-dynamic": "~10.0.0",
        "@angular/router": "~10.0.0",
        "@nativescript/angular": "~10.0.0",
        "@nativescript/core": "rc",
        "@nativescript/theme": "~2.3.0",
        "nativescript-appversion": "^1.4.4",
        "@nativescript/camera": "~5.0.0",
        "nativescript-couchbase-plugin": "^0.9.5",
        "nativescript-email": "^1.6.0",
        "nativescript-geolocation": "5.1.0",
        "nativescript-imagepicker": "^7.1.0",
        "nativescript-localstorage": "^2.0.1",
        "nativescript-ui-sidedrawer": "9.0.0-rc.1",
        "rxjs": "~6.6.0",
        "zone.js": "^0.10.3"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.1000.3",
        "@angular-devkit/build-ng-packagr": "^0.1000.3",
        "@angular/cli": "~10.0.0",
        "@angular/compiler-cli": "~10.0.0",
        "@angular/language-service": "~10.0.0",
        "@nativescript/schematics": "~10.0.2",
        "@ngtools/webpack": "~10.0.3",
        "@nativescript/webpack": "~2.1.3",
        "ng-packagr": "~10.0.2",
        "tslib": "^2.0.0",
        "tslint": "~6.1.2",
        "typescript": "~3.9.0"
    },
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets, link to playground demo or attach a runnable project)_

**Comment by kovalenkov** [comment]
It is reproducing also on 9.0.3 version
