### ISSUE TITLE
Nativescript-ui-dataform launch error

### ISSUE THREAD

**Issue by chelentos** [ProgressNS/nativescript-ui-feedback#1450]
# Tell us about the problem
Hello, I've installed nativescript-ui-dataform, and I'm getting this error when app runs on Android 29 (on iOS app freezing on start screen with NS logo):

> System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:46)
System.err: 
System.err: StackTrace: 
System.err: ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js(file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:46)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.js(file:///data/data/etu.schedule.app/files/app/vendor.js:69248:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-dataform/ui-dataform.common.js(file: node_modules/nativescript-ui-dataform/ui-dataform.common.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-dataform/ui-dataform.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-dataform/ui-dataform.js(file:///data/data/etu.schedule.app/files/app/vendor.js:73441:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-dataform/vue/index.js(file: node_modules/nativescript-ui-dataform/vue/index.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/etu.schedule.app/files/app/bundle.js:2011:37)
System.err:     at ./main.ts(file:///data/data/etu.schedule.app/files/app/bundle.js:2033:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/etu.schedule.app/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:46)
System.err: 
System.err: StackTrace: 
System.err: ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js(file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:46)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.js(file:///data/data/etu.schedule.app/files/app/vendor.js:69248:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-dataform/ui-dataform.common.js(file: node_modules/nativescript-ui-dataform/ui-dataform.common.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-dataform/ui-dataform.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-dataform/ui-dataform.js(file:///data/data/etu.schedule.app/files/app/vendor.js:73441:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-dataform/vue/index.js(file: node_modules/nativescript-ui-dataform/vue/index.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/etu.schedule.app/files/app/bundle.js:2011:37)
System.err:     at ./main.ts(file:///data/data/etu.schedule.app/files/app/bundle.js:2033:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/etu.schedule.app/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:237)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:46)
System.err: 
System.err: StackTrace: 
System.err: ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js(file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:46)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.js(file:///data/data/etu.schedule.app/files/app/vendor.js:69248:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-dataform/ui-dataform.common.js(file: node_modules/nativescript-ui-dataform/ui-dataform.common.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file: node_modules/nativescript-ui-dataform/ui-dataform.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-dataform/ui-dataform.js(file:///data/data/etu.schedule.app/files/app/vendor.js:73441:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-dataform/vue/index.js(file: node_modules/nativescript-ui-dataform/vue/index.js:1:0)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at fn(file: app/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/etu.schedule.app/files/app/bundle.js:2011:37)
System.err:     at ./main.ts(file:///data/data/etu.schedule.app/files/app/bundle.js:2033:30)
System.err:     at __webpack_require__(file: app/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file: app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/etu.schedule.app/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
System.err:     ... 8 more

### Which platform(s) does your issue occur on?
Android 29
iOs 13.2.2

### Please provide the following version numbers that your issue occurs with:
- **nativescript-ui-dataform**: 7.0.0
- **CLI:** 6.8.0
- **Cross-platform modules:** 6.5.1
- **Runtime(s):** **android** - 6.5.3, **ios** - 6.5.0

**Comment by hraynaud** [comment]
I'm having the exact same issue on ios.  I opened a ticket here: [https://github.com/nativescript-vue/nativescript-vue/issues/698](https://github.com/nativescript-vue/nativescript-vue/issues/698)

**Comment by toddanglin** [comment]
More or less the same problem I'm experiencing with `nativescript-ui-listview` after upgrading to v9.0.*. This feels like some kind of regression in the latest release. Downgrading the RadListView plugin to 8.2.0 made the problem go away.

I'm testing primarily on iOS with runtime `6.5.2` and `tns-core-modules` @ `6.5.15`. This is a {N} Core/TypeScript project with Webpack (no Angular). I have a feeling that may be the issue (especially if the latest release is working in Angular-based projects).

**Comment by toddanglin** [comment]
@stoskov Out of curiosity, are the {N} Rad plugins still updated/maintained by Progress? Or now by community?

**Comment by aranmohyeddin** [comment]
I also have this issue with RadAutoComplete.

**Comment by hraynaud** [comment]
@toddanglin do you know if there is a version of the the plugins that is safe to use. It looks like the problem is with nativescript-ui-autocomplete. I'm using the vue.js how would I downgrade?

**Comment by rigor789** [comment]
The latest version of the Pro UI has been published for the upcoming NativeScript 7.0 release, but accidentally got tagged as `latest`. We have re-tagged the ui packages to their correct versions. If you are having trouble, try deleting the dependency and adding it back with `npm i nativescript-ui-******@latest --save` and that should install the correct version.

**Comment by aranmohyeddin** [comment]
@rigor789 that solves one problem but I still get a similar error for nativescript-cardview for which I have also raised an [issue](https://github.com/nstudio/nativescript-cardview/issues/120) there.
```
TypeError: Could not load view for: nativecardview. TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
 at Module.../node_modules/@nstudio/nativescript-cardview/cardview-common.js (file:///data/data/com.app.app/files/app/vendor.js:52511:22)
    at __webpack_require__ (file:///data/data/com.app.app/files/app/runtime.js:751:30)
    at fn (file:///data/data/com.app.app/files/app/runtime.js:121:20)
    at Module.<anonymous> (file:///data/data/com.app.app/files/app/vendor.js:52562:74)
    at Module.../node_modules/@nstudio/nativescript-cardview/cardview.js (file:///data/data/com.app.app/files/app/vendor.js:52636:30)
    at __webpack_require__ (file:///data/data/com.app.app/files/app/runtime.js:751:30)
    at fn (file:///data/data/com.app.app/files/app/runtime.js:121:20)
    at Object.resolver (file:///data/data/com.app.app/files/app/bundle.js:7127:23)
    at getViewClass (file:///data/data/com.app.app/files/app/vendor.js:86458:18)
    at new ElementNode (file:///data/data/com.app.app/files/app/vendor.js:87305:21)
```

**Comment by aranmohyeddin** [comment]
downgrading to version `1.0.0` sovled it for me there too:
```
tns plugin add @nstudio/nativescript-cardview@1.0.0
```

**Comment by hraynaud** [comment]
same here I downgraded to v 6.1.0 of the nativescript-ui-dataform and it work.
