### ISSUE TITLE
Radlistview crashes IOS app

### ISSUE THREAD

**Issue by aljaz00** [ProgressNS/nativescript-ui-feedback#1462]
Hello,

I'm getting error below when serving `nativescript-vue` application. The error came up after upgrading radlistview from version `8.2.0` to `9.0.2`. Any suggestions on how to fix this error?

```JavaScript error:
file: node_modules/nativescript-ui-listview/ui-listview.common.js:65:57: JS ERROR TypeError: undefined is not a constructor (evaluating 'new _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["Property"]')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not a constructor (evaluating 'new _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["Property"]')
at
../node_modules/nativescript-ui-listview/ui-listview.common.js(file: node_modules/nativescript-ui-listview/ui-listview.common.js:65:57)
at __webpack_require__(file: src/mobile/webpack/bootstrap:74:0)
at ../node_modules/nativescript-ui-listview/ui-listview.ios.js(file: node_modules/nativescript-ui-listview/ui-listview.ios.js:1:0)
at __webpack_require__(file: src/mobile/webpack/bootstrap:74:0)
at ../node_modules/nativescript-ui-listview/vue/index.js(file: node_modules/nativescript-ui-listview/vue/index.js:1:0)
at __webpack_require__(file: src/mobile/webpack/bootstrap:74:0)
at file: src/mobile/main.native.ts:2:12
at ./main.native.ts(file:///app/bundle.js:10188:34)
at __webpack_require__(file: src/mobile/webpack/bootstrap:74:0)
at file:///app/bundle.js:14477:37
at __webpack_require__(file: src/mobile/webpack/bootstrap:74:0)
at checkDeferredModules(file: src/mobile/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/mobile/webpack/bootstrap:30:0)
at anonymous(file:///app/<…>
NativeScript caught signal 6.
Native Stack:
1   0x110a1c481 sig_handler(int)
2   0x7fff522f95fd _sigtramp
3   0x7fff521edf39 itoa64
4   0x7fff521e9b7c abort
5   0x7fff500ef858 abort_message
6   0x7fff500e0cbf demangling_unexpected_handler()
7   0x7fff512a1c0b _objc_terminate()
8   0x7fff500eec87 std::__terminate(void (*)())
9   0x7fff500f140b __cxa_get_exception_ptr
10  0x7fff500f13d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff512a1ad6 _objc_exception_destructor(void*)
12  0x1109cf0fd NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x110a1d824 -[TNSRuntime executeModule:referredBy:]
14  0x10f42ccb3 main
15  0x7fff5211c1fd start
16  0x1
```
* `Radlistview 9.0.2`
* `nativescript@6.8.0`
* `nativescript-vue`

**Comment by ngocnt1** [comment]
if you don't use pullToRefresh or other specific features of RadListView, you should try ListView now as i did, it's more smoothly , and not crashing

**Comment by romandragan** [comment]
Maybe related to https://github.com/NativeScript/ns-v8ios-runtime/issues/61 as well?
