### ISSUE TITLE
nativescript-ui-autocomplete doesn't work on iOs with NS7

### ISSUE THREAD

**Issue by nicolocaruso85** [ProgressNS/nativescript-ui-feedback#1475]
nativescript-ui-autocomplete on iOs with NativeScript 7 doesn't work.

I'm using @nativescript/core@7.0.8 and nativescript-ui-autocomplete@7.0.2 

NativeScript encountered a fatal error: Uncaught TypeError: this._ios.suggestionView.registerClassForCellWithReuseIdentifier is not a function
at
createNativeView(file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.ios.js:412:33)
at _setupUI(file: app/packages/core/ui/core/view-base/index.ts:782:21)
at (file: app/packages/core/ui/core/view-base/index.ts:831:9)
at eachChildView(file: app/packages/core/ui/layouts/layout-base-common.ts:125:18)
at eachChild(file: app/packages/core/ui/core/view/view-common.ts:867:7)
at _setupUI(file: app/packages/core/ui/core/view-base/index.ts:830:7)
at (file: app/packages/core/ui/core/view-base/index.ts:831:9)
at eachChildView(file: app/packages/core/ui/content-view/index.ts:77:3)
at eachChild(file: app/packages/core/ui/core/view/view-common.ts:867:7)
at _setupUI(file: app/packages/core/ui/core/view-base/index.ts:830:7)
at (file: app/packages/core/ui/core/view-base/index.ts:831:9)
at eachChildView(file: app/packages/core/ui/layouts/layout-base-common.ts:125:18)
at eachChild(file: app/packages/core/ui/core/view/view-common.ts:867:7)
at _setupUI(file: app/packages/core/ui/core/view-base/index.ts:830:7)
at (file: app/packages/core/ui/core/view-base/index.ts:831:9)
at eachChildView(file: app/packages/core/ui/content-view/index.ts:77:3)
at eachChildView(file: app/packages/core/ui/page/page-common.ts:145:8)
at eachChild(file: app/packages/core/ui/core/view/view-common.ts:867:7)
at _setupUI(file: app/packages/core/ui/core/view-base/index.ts:830:7)

**Comment by csimpi** [comment]
I'm having troubles on Android as well: 


`System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onSelectedPositionChange failed
System.err: Error: View already has a parent. View: SuggestionView(111) Parent: RadAutoCompleteTextView(109)
System.err:
System.err: StackTrace:
System.err: ZoneAwareError(file: node_modules\@nativescript\zone-js\zone-nativescript.js:1298:0)
System.err:     at _addView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:415:0)
System.err:     at adjustSuggestionView(file: node_modules\nativescript-ui-autocomplete\ui-autocomplete.android.js:643:0)
System.err:     at createNativeView(file: node_modules\nativescript-ui-autocomplete\ui-autocomplete.android.js:414:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:525:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at (file: node_modules\@nativescript\core\ui\core\view-base\index.js:567:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\content-view\index.js:65:0)
System.err:     at eachChildView(file: node_modules\@nativescript\core\ui\page\page-common.js:99:0)
System.err:     at eachChild(file: node_modules\@nativescript\core\ui\core\view\view-common.js:700:0)
System.err:     at _setupUI(file: node_modules\@nativescript\core\ui\core\view-base\index.js:566:0)
System.err:     at _addViewCore(file: node_modules\@nativescript\core\ui\core\view-base\index.js:429:0)
System.err:     at _addView(file: node_modules\@nativescript\core\ui\core\view-base\index.js:418:0)
System.err:     at onCreateView(file: node_modules\@nativescript\core\ui\frame\index.android.js:738:0)
System.err:     at onCreateView(file: node_modules\@nativescript\core\ui\frame\fragment.android.js:25:0)
System.err:     at commitCurrentTransaction(file: node_modules\@nativescript\core\ui\bottom-navigation\index.android.js:369:0)
System.err:     at changeTab(file: node_modules\@nativescript\core\ui\bottom-navigation\index.android.js:387:0)
System.err:     at BottomNavigationBarImplementation.onSelectedPositionChange(file: node_modules\@nativescript\core\ui\bottom-navigation\index.android.js:122:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.org.nativescript.widgets.BottomNavigationBar_vendor_120521_28_BottomNavigationBarImplementation.onSelectedPositionChange(BottomNavigationBar_vendor_120521_28_BottomNavigationBarImplementation.java:39)
System.err:     at org.nativescript.widgets.BottomNavigationBar.setSelectedPosition(BottomNavigationBar.java:289)
System.err:     at org.nativescript.widgets.BottomNavigationBar$TabClickListener.onClick(BottomNavigationBar.java:302)
System.err:     at android.view.View.performClick(View.java:7359)
System.err:     at android.view.View.performClickInternal(View.java:7325)
System.err:     at android.view.View.access$3200(View.java:846)
System.err:     at android.view.View$PerformClick.run(View.java:27807)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7073)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
`

**Comment by aashaya** [comment]
I'm having issues with NS7 autocomplete.  Were anyone able to figure out any workaround or fix?

ns version : 7.0.10
npm: 6.14.4
node: v12.16.2

platform:
iOS - 7.0.1
Android - 7.0.0

package.json
    "nativescript-ui-autocomplete": "^7.0.2",
    "nativescript-ui-dataform": "^7.0.2",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-ui-sidedrawer": "^9.0.3"

**** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: this._ios.suggestionView.registerClassForCellWithReuseIdentifier is not a function
at
createNativeView(file: node_modules/nativescript-ui-autocomplete/ui-autocomplete.ios.js:412:0)
at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:525:0)
at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
at eachChildView(file: node_modules/@nativescript/core/ui/content-view/index.js:65:0)
at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
at <…>

**Comment by aashaya** [comment]
@nicolocaruso85 were you able find the workaround?
