### ISSUE TITLE
_nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor

### ISSUE THREAD

**Issue by Skillnter** [ProgressNS/nativescript-ui-feedback#1478]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._

Issue with TokenModel. 
`this.categories.push(new TokenModel(items[i].name, undefined))`

Whenever I initiate the TokenModel for dataItems, I get the following error breaking my module:

> JS: ERROR Error: Uncaught (in promise): TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
> JS: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
> JS:     at Module.../node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js (file: node_modules\nativescript-ui-autocomplete\ui-autocomplete.common.js:60:0)
> JS:     at __webpack_require__ (file: src\webpack\bootstrap:750:0)
> JS:     at fn (file: src\webpack\bootstrap:120:0)
> JS:     at Module.<anonymous> (file: node_modules\nativescript-ui-autocomplete\ui-autocomplete.android.js:1:0)
> JS:     at Module.../node_modules/nativescript-ui-autocomplete/ui-autocomplete.js (file:///data/data/org.nativescript.networkdr/files/app/vendor.15aaa296311780256f4b.hot-update.js:1789:30)
> JS:     at __webpack_require__ (file: src\webpack\bootstrap:750:0)
> JS:     at fn (fil...

If I just comment `this.categories.push(new TokenModel(items[i].name, undefined))` this line, Everything work except the autocomplete. 

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_
I only got android. It is not working on android.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** (the version of nativescript-ui-* in the `package.json`)"nativescript-ui-autocomplete": "^7.0.2",
- **CLI:** (run `tns --version` to fetch it)6.7.8
- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)6.5.20
- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)android

### Please tell us how to recreate the issue in as much detail as possible.
1. I used the code from here

> https://github.com/ProgressNS/nativescript-ui-samples-angular/tree/master/autocomplete/app/examples/completion-mode

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets, link to playground demo or attach a runnable project)_

**Comment by Skillnter** [comment]
Also getting same error on Nativescriptuichart

> System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
> System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
> System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:219)
> System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
> System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
> System.err:     at android.os.Looper.loop(Looper.java:214)
> System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
> System.err:     at java.lang.reflect.Method.invoke(Native Method)
> System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> System.err: Caused by: com.tns.NativeScriptException: Error calling module function
> System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
> System.err: File: (file: node_modules\nativescript-ui-chart\visualization\parts\chart-label-style.common.js:4:0)
> System.err:
> System.err: StackTrace:
> System.err: ../node_modules/nativescript-ui-chart/visualization/parts/chart-label-style.common.js(file: node_modules\nativescript-ui-chart\visualization\parts\chart-label-style.common.js:4:0)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at ../node_modules/nativescript-ui-chart/visualization/views/chart-series.common.js(file: node_modules\nativescript-ui-chart\visualization\views\chart-series.common.js:1:0)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at ../node_modules/nativescript-ui-chart/initializers/chart-initializers.js(file: node_modules\nativescript-ui-chart\initializers\chart-initializers.android.js:1:0)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at ../node_modules/nativescript-ui-chart/ui-chart.common.js(file: node_modules\nativescript-ui-chart\ui-chart.common.js:1:0)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at (file: node_modules\nativescript-ui-chart\ui-chart.android.js:1:0)
> System.err:     at ../node_modules/nativescript-ui-chart/ui-chart.js(file:///data/data/org.nativescript.networkdr/files/app/vendor.js:172269:30)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at ../node_modules/nativescript-ui-chart/angular/fesm2015/nativescript-ui-chart-angular.js(file: node_modules\nativescript-ui-chart\angular\fesm2015\nativescript-ui-chart-angular.js:1:0)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at ./app/app.module.ts(file: src\app\app.module.ts:1:0)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at fn(file: src\webpack\bootstrap:120:0)
> System.err:     at (file:///data/data/org.nativescript.networkdr/files/app/bundle.js:384:73)
> System.err:     at ./main.ts(file:///data/data/org.nativescript.networkdr/files/app/bundle.js:450:30)
> System.err:     at __webpack_require__(file: src\webpack\bootstrap:750:0)
> System.err:     at checkDeferredModules(file: src\webpack\bootstrap:43:0)
> System.err:     at webpackJsonpCallback(file: src\webpack\bootstrap:30:0)
> System.err:     at (file:///data/data/org.nativescript.networkdr/files/app/bundle.js:2:57)
> System.err:     at require(:1:266)

**Comment by Skillnter** [comment]
https://docs.nativescript.org/angular/ui/ng-components/ng-dataform/getting-started#adding-a-raddataform-to-your-components-template

Can't use RadDataForm too as dependency on autocomplete. How can this be resolved? Will it ever be updated??

**Comment by Skillnter** [comment]
Full project crashed. Stopped working :/

now typings messed up automatically. 

whole project messed up after running npm install @nativescript/core 
What is wrong with nativescript. No proper documentation. No proper libraries. No proper support. No standard for libraries...Everything is messed up and no help as well for explanations.

**Comment by Skillnter** [comment]
> tns create my-drawer-ng --template tns-template-drawer-navigation-ng

Nothing is working. Creating new repo but everything is messed up in nativescript

> ERROR in nativescript.config.ts:1:10 - error TS2305: Module '"F:/test/network/node_modules/@nativescript/core"' has no exported member 'NativeScriptConfig'.
> 
> 1 import { NativeScriptConfig } from '@nativescript/core';

**Comment by Skillnter** [comment]
tns add the latest version of the plugin. There is some serious issue related to versioning. 
tns does not add a compatible version of plugins which is causing the whole problem. 

Tried with different versions to find a compatible / working one. Need proper versioning and documentation for this.

**Comment by nmandyam** [comment]
Identical probem, possibly from another location in the plugin. Was working perfectly OK on Android till I recompiled. The recompile has nothing to do with the page JS or XML that is now crashing. In search of a fix, I upgraded tns-android from 6.3.1 (where it was working OK till the recompile) to 6.5.3, still fails. 
One related input, if it helps: I had `dataModelModule = require("nativescript-ui-chart")` in my JS and that caused the app to crash after recompile (with '_nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor' as soon as control was passed to the page. But since I don't need the chart in my JS, I commented that out (my XML still has it, of course). So now the JS loads, does its pageLoaded event and THEN crashes.

`
System.err: Error: Building UI from XML. @pages/vol_stats/vol_stats.xml:51:29
System.err:  > Module 'nativescript-ui-chart' not found for element 'nativescript-ui-chart:RadCartesianChart'.
System.err:    > _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: 
System.err: StackTrace:
System.err: ScopeError(file: node_modules/@nativescript/core/utils/debug.js:63:0)
System.err: 	at SourceError(file: node_modules/@nativescript/core/utils/debug.js:74:0)
System.err: 	at (file: node_modules/@nativescript/core/ui/builder/builder.js:224:0)
System.err: 	at (file: node_modules/@nativescript/core/ui/builder/builder.js:292:0)
System.err: 	at push.../node_modules/@nativescript/core/ui/builder/builder.js.XmlArgsReplay.replay(file: node_modules/@nativescript/core/ui/builder/builder.js:287:0)
System.err: 	at (file: node_modules/@nativescript/core/ui/builder/builder.js:372:0)
System.err: 	at push.../node_modules/@nativescript/core/ui/builder/builder.js.Builder.parse(file: node_modules/@nativescript/core/ui/builder/builder.js:46:0)
System.err: 	at createView(file: node_modules/@nativescript/core/ui/list-view/list-view-common.js:30:0)
System.err: 	at ListViewAdapter.getView(file: node_modules/@nativescript/core/ui/list-view/list-view.android.js:247:0)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err: 	at com.tns.gen.android.widget.BaseAdapter_vendor_49712_32_ListViewAdapter.getView(BaseAdapter_vendor_49712_32_ListViewAdapter.java:39)
System.err: 	at android.widget.AbsListView.obtainView(AbsListView.java:2372)
System.err: 	at android.widget.ListView.makeAndAddView(ListView.java:2052)
System.err: 	at android.widget.ListView.fillDown(ListView.java:786)
System.err: 	at android.widget.ListView.fillFromTop(ListView.java:847)
System.err: 	at android.widget.ListView.layoutChildren(ListView.java:1798)
System.err: 	at android.widget.AbsListView.onLayout(AbsListView.java:2171)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err: 	at android.os.Handler.handleCallback(Handler.java:789)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
JS: 01-Nov 11:56:54.382 - Uncaught system error... 
`

**Comment by Skillnter** [comment]
> Identical probem, possibly from another location in the plugin. Was working perfectly OK on Android till I recompiled. The recompile has nothing to do with the page JS or XML that is now crashing. In search of a fix, I upgraded tns-android from 6.3.1 (where it was working OK till the recompile) to 6.5.3, still fails. The specific line it refers to in the error message is this:
> `<chart:RadCartesianChart height="{{ height, height }}" verticalAlignment="top" >`.
> 
> I use Core, no Angular or Vue.
> 
> One related input, if it helps: I had `dataModelModule = require("nativescript-ui-chart")` in my JS and that caused the app to crash after recompile (with `_nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor` as soon as control was passed to the page. But since I don't need the chart in my JS, I commented that out (my XML still has it, of course). So now the JS loads, does its pageLoaded event and THEN crashes.
> 
> `System.err: Error: Building UI from XML. @pages/vol_stats/vol_stats.xml:51:29 System.err: > Module 'nativescript-ui-chart' not found for element 'nativescript-ui-chart:RadCartesianChart'. System.err: > _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor System.err: System.err: StackTrace: System.err: ScopeError(file: node_modules/@nativescript/core/utils/debug.js:63:0) System.err: at SourceError(file: node_modules/@nativescript/core/utils/debug.js:74:0) System.err: at (file: node_modules/@nativescript/core/ui/builder/builder.js:224:0) System.err: at (file: node_modules/@nativescript/core/ui/builder/builder.js:292:0) System.err: at push.../node_modules/@nativescript/core/ui/builder/builder.js.XmlArgsReplay.replay(file: node_modules/@nativescript/core/ui/builder/builder.js:287:0) System.err: at (file: node_modules/@nativescript/core/ui/builder/builder.js:372:0) System.err: at push.../node_modules/@nativescript/core/ui/builder/builder.js.Builder.parse(file: node_modules/@nativescript/core/ui/builder/builder.js:46:0) System.err: at createView(file: node_modules/@nativescript/core/ui/list-view/list-view-common.js:30:0) System.err: at ListViewAdapter.getView(file: node_modules/@nativescript/core/ui/list-view/list-view.android.js:247:0) System.err: at com.tns.Runtime.callJSMethodNative(Native Method) System.err: at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286) System.err: at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173) System.err: at com.tns.Runtime.callJSMethod(Runtime.java:1160) System.err: at com.tns.Runtime.callJSMethod(Runtime.java:1138) System.err: at com.tns.Runtime.callJSMethod(Runtime.java:1134) System.err: at com.tns.gen.android.widget.BaseAdapter_vendor_49712_32_ListViewAdapter.getView(BaseAdapter_vendor_49712_32_ListViewAdapter.java:39) System.err: at android.widget.AbsListView.obtainView(AbsListView.java:2372) System.err: at android.widget.ListView.makeAndAddView(ListView.java:2052) System.err: at android.widget.ListView.fillDown(ListView.java:786) System.err: at android.widget.ListView.fillFromTop(ListView.java:847) System.err: at android.widget.ListView.layoutChildren(ListView.java:1798) System.err: at android.widget.AbsListView.onLayout(AbsListView.java:2171) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178) System.err: at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178) System.err: at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178) System.err: at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178) System.err: at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178) System.err: at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222) System.err: at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) System.err: at android.widget.FrameLayout.onLayout(FrameLayout.java:261) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) System.err: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) System.err: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) System.err: at android.widget.FrameLayout.onLayout(FrameLayout.java:261) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) System.err: at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) System.err: at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) System.err: at android.widget.FrameLayout.onLayout(FrameLayout.java:261) System.err: at com.android.internal.policy.DecorView.onLayout(DecorView.java:758) System.err: at android.view.View.layout(View.java:19590) System.err: at android.view.ViewGroup.layout(ViewGroup.java:6053) System.err: at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484) System.err: at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200) System.err: at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386) System.err: at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733) System.err: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911) System.err: at android.view.Choreographer.doCallbacks(Choreographer.java:723) System.err: at android.view.Choreographer.doFrame(Choreographer.java:658) System.err: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) System.err: at android.os.Handler.handleCallback(Handler.java:789) System.err: at android.os.Handler.dispatchMessage(Handler.java:98) System.err: at android.os.Looper.loop(Looper.java:164) System.err: at android.app.ActivityThread.main(ActivityThread.java:6541) System.err: at java.lang.reflect.Method.invoke(Native Method) System.err: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) JS: 01-Nov 11:56:54.382 - Uncaught system error... `

Hi, I am still struggling with plugins but i made the ui-chart to work. All I did i imported the latest version and keep rolling back till I find the working one. 

Note: After every rollback make sure to make a clean new build. Took me alot to find all bugs. 

Better versioning and documentation can really help in decreasing the debug and development time. All these features but it takes a long time to get them working :P

**Comment by nmandyam** [comment]
Thanks, went all the way back to 5.0.0 to make it work on Android. But that still fails on iOS. Gawd!

**Comment by Skillnter** [comment]
> Thanks, went all the way back to 5.0.0 to make it work on Android. But that still fails on iOS. Gawd!

I Wish they can actually look at this issue. 

No matter what they do in the future, if this problem is not resolved, we will have to keep on struggling with everything even more :P................more versions..........more rollbacks.............more issues....  😭 😞
